---
title: "p8105_hw6_fx2184"
author: "Fei"
date: "2022-12-03"
output: github_document
---
```{r setup, include = FALSE}
library(tidyverse)
library(viridis)
```


## Problem 2 Washingtong Post - Homicides 
```{r}
#import the dataset 
url = "https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv"
homicides_raw = read_csv(url)
```

```{r}
# create variable city_state and clean the dataset
homicides = homicides_raw %>% 
  janitor::clean_names() %>% 
  mutate(city_state = str_c(city, state,sep = ", "),
         victim_age = as.numeric(victim_age),
         victim_race = fct_relevel(victim_race, "White"),
         resolved = case_when(
           disposition == "Closed by arrest" ~ 1,
           disposition ==  "Open/No arrest" ~ 0,
           disposition ==  "Closed without arrest" ~ 0
         ),
         reported_date = as.Date(as.character(reported_date), format = "%Y%m%d")) %>% 
  filter(!(city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO","Tulsa, AL")))%>% 
  filter(victim_race  %in% c("White", "Black"))
```

```{r}
Baltimoe_fit_logistic = homicides %>% 
    filter(city_state  %in% c("Baltimore, MD")) %>% 
    glm(resolved ~ victim_age + victim_sex +victim_race, data = ., family = binomial()) 

Baltimoe_fit_logistic%>% 
  broom::tidy(conf.int = T) %>% 
  mutate(OR = exp(estimate),
         CI_Lower = exp(conf.low),
         CI_Upper = exp(conf.high)) %>%
  select(term, log_OR = estimate, OR, CI_Lower, CI_Upper, p.value) %>% 
  knitr::kable(align = "lrr",
               col.names = c("Term","Estimate","OR", "95% CI Lower", "95% CI Upper", "P-value"),
               digits = 3)

```

